### ISSUE TITLE
Unable to pass multiple apps alerts through from alertmanager

### ISSUE THREAD

**Issue by nusnewob** [summerwind/alertmanager-sentry-gateway#11]
I'm trying to setup alertmanager to forward multiple apps errors to Sentry, therefore the webhook `url` needs to be dynamic, I'm exposing `.Labels.sentry_io_app` as Sentry `<project_id>`, see configs below.
However, Alertmanager webhook `url` parameter doesn't support using template syntax ([see issue](https://github.com/prometheus/alertmanager/issues/684)). Is there any other way to pass `<project_id>` to the gateway?

Example config
```
receivers:
- name: team
  webhook_configs:
  - url: 'http://127.0.0.1:9096/{{ .Labels.sentry_io_app }}'
    send_resolved: false
```
